server:
  port: 8001
spring:
  profiles:
    active: dev
  application:
    name: student
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
management:
  tracing:
    sampling:
      probability: 1.0